version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
  - package-ecosystem: pip
    directory: /
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
